"use client";
import Icons from "@/components/Icons";
import dayjs from "dayjs";
import "dayjs/locale/ko";
dayjs.locale("ko");
import { useState, useEffect } from "react";
import Modal_Button from "@/components/Modal_Button";
import Header from "@/components/Header";
import Navbar from "@/components/Navbar";
export const metadata = {
  title: "The World Alarm",
  description: "generated by fo_rdangIT",
};
export default function ClockPage() {
  let year: string = dayjs(new Date()).format("YYYY");
  let month: string = dayjs(new Date()).format("MM");
  let day: string = dayjs(new Date()).format("DD");
  let week: string = dayjs(new Date()).format("dddd");
  let hour: string = dayjs(new Date()).format("HH");
  let minute: string = dayjs(new Date()).format("mm");
  let second: string = dayjs(new Date()).format("ss");

  const [nowYear, setNowYear] = useState(year);
  const [nowMonth, setNowMonth] = useState(month);
  const [nowDay, setNowDay] = useState(day);
  const [nowWeek, setNowWeek] = useState(week);
  const [nowHour, setNowHour] = useState(hour);
  const [nowMinute, setNowMinute] = useState(minute);
  const [nowSecond, setNowSecond] = useState(second);
  useEffect(() => {
    const timer = setInterval(() => {
      setNowYear(year);
      setNowMonth(month);
      setNowDay(day);
      setNowWeek(week);
      setNowHour(hour);
      setNowMinute(minute);
      setNowSecond(second);
    }, 1000);
    return () => clearInterval(timer);
  }, [year, month, day, week, hour, minute, second]);
  console.log("확인");

  return (
    <div>
      <Header />
      <div className="flex">
        <div className="h-84">
          <Navbar />
        </div>
        <div className="bg-orange-50 w-full">
          <div className="flex justify-end items-start pt-8 pr-3">
            <Icons />
          </div>
          <div className="py-40 text-center pr-4">
            <div className="mb-4">
              <p
                className="text-3xl text-gray-500 ml-20"
                suppressHydrationWarning
              >
                {nowYear}년 {nowMonth}월 {nowDay}일 {nowWeek}
              </p>
            </div>
            <div>
              <span className="text-5xl mr-4" suppressHydrationWarning>
                {Number(nowHour) > 12 ? `오후` : `오전`}
              </span>
              <span className="text-9xl" suppressHydrationWarning>
                {nowHour}:{nowMinute}:{nowSecond}
              </span>
              <Modal_Button />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
